AUTOCOMMIT OFF;

CREATE TABLE T_KJV (
	ID INTEGER NOT NULL,
	B INTEGER NOT NULL,
	C INTEGER NOT NULL,
	V INTEGER NOT NULL,
	T LONG VARCHAR NOT NULL
);
ALTER TABLE T_KJV
  ADD CONSTRAINT T_KJV_PK Primary Key (
   ID);

CREATE TABLE KEY_BIBLE_ENGLISH(
	b INTEGER NOT NULL, -- Book #
	n LONG VARCHAR NOT NULL, -- Name
	t LONG VARCHAR NOT NULL, -- Which Testament this book is in
	g INTEGER NOT NULL -- A genre ID to identify the type of book this is
);

CREATE TABLE Quran (
	ID INTEGER NOT NULL,
	DatabaseID INTEGER NOT NULL,
	SuraID INTEGER NOT NULL,
	VerseID INTEGER NOT NULL,
	AyahText LONG VARCHAR NOT NULL
);
ALTER TABLE Quran
  ADD CONSTRAINT QURAN_PK Primary Key (
   ID);


COMMIT;
