insert into KEY_BIBLE_ENGLISH values (1, 'Genesis', 'OT', 1);
insert into KEY_BIBLE_ENGLISH values (2, 'Exodus', 'OT', 1);
insert into KEY_BIBLE_ENGLISH values (3, 'Leviticus', 'OT', 1);
insert into KEY_BIBLE_ENGLISH values (4, 'Numbers', 'OT', 1);
insert into KEY_BIBLE_ENGLISH values (5, 'Deuteronomy', 'OT', 1);
insert into KEY_BIBLE_ENGLISH values (6, 'Joshua', 'OT', 2);
insert into KEY_BIBLE_ENGLISH values (7, 'Judges', 'OT', 2);
insert into KEY_BIBLE_ENGLISH values (8, 'Ruth', 'OT', 2);
insert into KEY_BIBLE_ENGLISH values (9, '1 Samuel', 'OT', 2);
insert into KEY_BIBLE_ENGLISH values (10, '2 Samuel', 'OT', 2);
insert into KEY_BIBLE_ENGLISH values (11, '1 Kings', 'OT', 2);
insert into KEY_BIBLE_ENGLISH values (12, '2 Kings', 'OT', 2);
insert into KEY_BIBLE_ENGLISH values (13, '1 Chronicles', 'OT', 2);
insert into KEY_BIBLE_ENGLISH values (14, '2 Chronicles', 'OT', 2);
insert into KEY_BIBLE_ENGLISH values (15, 'Ezra', 'OT', 2);
insert into KEY_BIBLE_ENGLISH values (16, 'Nehemiah', 'OT', 2);
insert into KEY_BIBLE_ENGLISH values (17, 'Esther', 'OT', 2);
insert into KEY_BIBLE_ENGLISH values (18, 'Job', 'OT', 3);
insert into KEY_BIBLE_ENGLISH values (19, 'Psalms', 'OT', 3);
insert into KEY_BIBLE_ENGLISH values (20, 'Proverbs', 'OT', 3);
insert into KEY_BIBLE_ENGLISH values (21, 'Ecclesiastes', 'OT', 3);
insert into KEY_BIBLE_ENGLISH values (22, 'Song of Solomon', 'OT', 3);
insert into KEY_BIBLE_ENGLISH values (23, 'Isaiah', 'OT', 4);
insert into KEY_BIBLE_ENGLISH values (24, 'Jeremiah', 'OT', 4);
insert into KEY_BIBLE_ENGLISH values (25, 'Lamentations', 'OT', 4);
insert into KEY_BIBLE_ENGLISH values (26, 'Ezekiel', 'OT', 4);
insert into KEY_BIBLE_ENGLISH values (27, 'Daniel', 'OT', 4);
insert into KEY_BIBLE_ENGLISH values (28, 'Hosea', 'OT', 4);
insert into KEY_BIBLE_ENGLISH values (29, 'Joel', 'OT', 4);
insert into KEY_BIBLE_ENGLISH values (30, 'Amos', 'OT', 4);
insert into KEY_BIBLE_ENGLISH values (31, 'Obadiah', 'OT', 4);
insert into KEY_BIBLE_ENGLISH values (32, 'Jonah', 'OT', 4);
insert into KEY_BIBLE_ENGLISH values (33, 'Micah', 'OT', 4);
insert into KEY_BIBLE_ENGLISH values (34, 'Nahum', 'OT', 4);
insert into KEY_BIBLE_ENGLISH values (35, 'Habakkuk', 'OT', 4);
insert into KEY_BIBLE_ENGLISH values (36, 'Zephaniah', 'OT', 4);
insert into KEY_BIBLE_ENGLISH values (37, 'Haggai', 'OT', 4);
insert into KEY_BIBLE_ENGLISH values (38, 'Zechariah', 'OT', 4);
insert into KEY_BIBLE_ENGLISH values (39, 'Malachi', 'OT', 4);
insert into KEY_BIBLE_ENGLISH values (40, 'Matthew', 'NT', 5);
insert into KEY_BIBLE_ENGLISH values (41, 'Mark', 'NT', 5);
insert into KEY_BIBLE_ENGLISH values (42, 'Luke', 'NT', 5);
insert into KEY_BIBLE_ENGLISH values (43, 'John', 'NT', 5);
insert into KEY_BIBLE_ENGLISH values (44, 'Acts', 'NT', 6);
insert into KEY_BIBLE_ENGLISH values (45, 'Romans', 'NT', 7);
insert into KEY_BIBLE_ENGLISH values (46, '1 Corinthians', 'NT', 7);
insert into KEY_BIBLE_ENGLISH values (47, '2 Corinthians', 'NT', 7);
insert into KEY_BIBLE_ENGLISH values (48, 'Galatians', 'NT', 7);
insert into KEY_BIBLE_ENGLISH values (49, 'Ephesians', 'NT', 7);
insert into KEY_BIBLE_ENGLISH values (50, 'Philippians', 'NT', 7);
insert into KEY_BIBLE_ENGLISH values (51, 'Colossians', 'NT', 7);
insert into KEY_BIBLE_ENGLISH values (52, '1 Thessalonians', 'NT', 7);
insert into KEY_BIBLE_ENGLISH values (53, '2 Thessalonians', 'NT', 7);
insert into KEY_BIBLE_ENGLISH values (54, '1 Timothy', 'NT', 7);
insert into KEY_BIBLE_ENGLISH values (55, '2 Timothy', 'NT', 7);
insert into KEY_BIBLE_ENGLISH values (56, 'Titus', 'NT', 7);
insert into KEY_BIBLE_ENGLISH values (57, 'Philemon', 'NT', 7);
insert into KEY_BIBLE_ENGLISH values (58, 'Hebrews', 'NT', 7);
insert into KEY_BIBLE_ENGLISH values (59, 'James', 'NT', 7);
insert into KEY_BIBLE_ENGLISH values (60, '1 Peter', 'NT', 7);
insert into KEY_BIBLE_ENGLISH values (61, '2 Peter', 'NT', 7);
insert into KEY_BIBLE_ENGLISH values (62, '1 John', 'NT', 7);
insert into KEY_BIBLE_ENGLISH values (63, '2 John', 'NT', 7);
insert into KEY_BIBLE_ENGLISH values (64, '3 John', 'NT', 7);
insert into KEY_BIBLE_ENGLISH values (65, 'Jude', 'NT', 7);
insert into KEY_BIBLE_ENGLISH values (66, 'Revelation', 'NT', 8);
